[package]
name = "daytime-theme-scheduler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyprland = "0.3.13"
reqwest = "0.12.4"
tokio = { version = "1.38.0", features = ["full"] }
